name: CI

on:
  # allows us to run workflows manually
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  main:
    runs-on: ubuntu-18.04
    name: 'Trelis Svalinn Plugin 17.1 Build'


    steps:
      -
        uses: actions/checkout@v2

      -
        name: Environment Variables
        run: |
          echo "CURRENT=$(pwd)" >> $GITHUB_ENV
          echo "PLUGIN_ABS_PATH=" >> $GITHUB_ENV
          echo "SCRIPTPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          echo "PLUGIN_ABS_PATH=$GITHUB_WORKSPACE/.." >> $GITHUB_ENV
          source $GITHUB_WORKSPACE/script/linux_share_build.sh

      -
        name: Apt dependencies
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y g++ libtool libeigen3-dev libhdf5-dev patchelf git cmake

      -
        name: Build MOAB
        shell: bash
        run: |
          cd ${PLUGIN_ABS_PATH}
          mkdir -pv moab/bld
          cd moab
          git clone https://bitbucket.org/fathomteam/moab -b Version5.1.0
          cd bld
          cmake ../moab -DENABLE_HDF5=ON \
                  -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/hdf5/serial \
                  -DBUILD_SHARED_LIBS=ON \
                  -DENABLE_BLASLAPACK=OFF \
                  -DENABLE_FORTRAN=OFF \
                  -DCMAKE_CXX_FLAGS=-D_GLIBCXX_USE_CXX11_ABI=0 \
                  -DCMAKE_INSTALL_PREFIX=${PLUGIN_ABS_PATH}/moab

          make -j`grep -c processor /proc/cpuinfo`
          make install
          cd ../..
          rm -rf moab/moab moab/bld

      -
        name: build DAGMC
        shell: bash
        run: |
          cd ${PLUGIN_ABS_PATH}
          mkdir -pv DAGMC/bld
          cd DAGMC
          git clone https://github.com/bam241/DAGMC -b build_exe
          cd bld
          cmake ../DAGMC -DCMAKE_CXX_FLAGS=-D_GLIBCXX_USE_CXX11_ABI=0 \
                      -DMOAB_DIR=${PLUGIN_ABS_PATH}/moab \
                      -DBUILD_UWUW=ON \
                      -DBUILD_TALLY=OFF \
                      -DBUILD_BUILD_OBB=OFF \
                      -DBUILD_MAKE_WATERTIGHT=ON \
                      -DBUILD_SHARED_LIBS=ON \
                      -DBUILD_STATIC_LIBS=OFF \
                      -DBUILD_EXE=OFF \
                      -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
                      -DCMAKE_BUILD_TYPE=Release \
                      -DCMAKE_INSTALL_PREFIX=${PLUGIN_ABS_PATH}/DAGMC
          make -j`grep -c processor /proc/cpuinfo`
          make install
          cd ../..
          rm -rf DAGMC/DAGMC DAGCM/bld

      - name: Trelis setup
        shell: bash
        env:   
          TRELIS_DEB_URL: ${{ secrets.TRELIS_DEB_URL }}
          TRELIS_SDK_URL: ${{ secrets.TRELIS_SDK_URL }}
        run: |
          cd ${PLUGIN_ABS_PATH}
          echo "$TRELIS_DEB_URL"
          curl -L https://uwmadison.box.com/shared/static/${TRELIS_DEB_URL}.deb --output trelis.deb
          sudo dpkg -i trelis.deb
          cd /opt
          curl -L https://uwmadison.box.com/shared/static/${TRELIS_SDK_URL}.gz --output trelis_sdk.tar.gz
          tar -zxvf trelis_sdk.tar.gz


      -
        name: build plugin
        shell: bash
        run: |
          source $GITHUB_WORKSPACE/script/linux_share_build.sh
          build_plugin 17.1.0

      -
        name: prepare pkg
        shell: bash
        run: |
          source $GITHUB_WORKSPACE/script/linux_share_build.sh
          build_plugin_pkg 17.1.0

  finish:
    needs: main
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
