name: MACOS

on:
  # allows us to run workflows manually
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  main:
    runs-on: macos-10.15
    name: 'Trelis Svalinn Plugin 17.1 Build for Macos'

    steps:
      - uses: actions/checkout@v2

      - name: Environment Variables
        run: |
          echo "CURRENT=$(pwd)" >> $GITHUB_ENV
          echo "PLUGIN_ABS_PATH=" >> $GITHUB_ENV
          echo "SCRIPTPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          echo "PLUGIN_ABS_PATH=$GITHUB_WORKSPACE/.." >> $GITHUB_ENV

      - name: Brew dependencies
        shell: bash
        run: |
          brew install eigen hdf5 gcc@6 
   
      - name: Build MOAB
        shell: bash
        run: |
          cd ${PLUGIN_ABS_PATH}
          mkdir -pv moab/bld
          cd moab
          git clone https://bitbucket.org/fathomteam/moab -b Version5.1.0
          cd bld
          cmake ../moab -DENABLE_HDF5=ON \
                    -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/hdf5/serial \
                    -DBUILD_SHARED_LIBS=OFF \
                    -DENABLE_BLASLAPACK=OFF -DENABLE_FORTRAN=OFF \
                    -DCMAKE_CXX_FLAGS=-D_GLIBCXX_USE_CXX11_ABI=0 \
                    -DCMAKE_INSTALL_PREFIX=${PLUGIN_ABS_PATH}/moab
          make -j
          make install
          cd ../..
          rm -rf moab/moab moab/bld

      - name: Build DAGMC
        shell: bash
        run: |
          cd ${PLUGIN_ABS_PATH}
          mkdir -pv DAGMC/bld
          cd DAGMC
          git clone https://github.com/bam241/DAGMC -b build_exe
          cd bld
          cmake ../DAGMC -DCMAKE_CXX_FLAGS=-D_GLIBCXX_USE_CXX11_ABI=0 \
                        -DMOAB_DIR=${PLUGIN_ABS_PATH}/moab \
                        -DBUILD_UWUW=ON \
                        -DBUILD_TALLY=OFF \
                        -DBUILD_BUILD_OBB=OFF \
                        -DBUILD_MAKE_WATERTIGHT=ON \
                        -DBUILD_SHARED_LIBS=OFF \
                        -DBUILD_STATIC_LIBS=ON \
                        -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
                        -DCMAKE_BUILD_TYPE=Release \
                        -DCMAKE_INSTALL_PREFIX=${PLUGIN_ABS_PATH}/DAGMC
          make -j
          make install
          cd ../..
          rm -rf DAGMC/DAGMC DAGCM/bld

      - name: Trelis setup
        shell: bash
        env:   
          TRELIS_DEB_URL: ${{ secrets.MAC_TRELIS_17 }}
          TRELIS_SDK_URL: ${{ secrets.MAC_TRELIS_SDK_17 }}
          TRELIS_INSTALL_LOC: "/Applications/Trelis-17.1.app/Contents"
        run: |
          cd ${PLUGIN_ABS_PATH}
          curl -L https://uwmadison.box.com/shared/static/${TRELIS_DEB_URL}.dmg --output trelis.dmg
          hdiutil convert trelis.dmg -format UDTO -o trelis_eula.dmg
          ls
          hdiutil attach trelis_eula.dmg.cdr
          ls /Volumes/Trelis-17.1.0-Mac64/Trelis-17.1.app
          mv /Volumes/Trelis-17.1.0-Mac64/Trelis-17.1.app /Applications/
          hdiutil detach /Volumes/Trelis-17.1.0-Mac64
          rm -rf trelis.dmg
          cd $TRELIS_INSTALL_LOC
          curl -L https://uwmadison.box.com/shared/static/${TRELIS_SDK_URL}.gz --output trelis_sdk.tar.gz
          tar -xzf trelis_sdk.tar.gz
          mv Trelis-17.1/* ./
          mv Trelis-17.1.app/Contents/MacOS/* MacOS/
          mv bin/* MacOS/
          rm -rf bin Trelis-17.1.app
          ln -s MacOS bin
          ln -s /Applications/Trelis-17.1.app/Contents/include /Applications/include
          echo "TRELIS_INSTALL_LOC=$TRELIS_INSTALL_LOC" >> $GITHUB_ENV
       
      - name: Build plugin
        shell: bash
        run: |
          cd ${PLUGIN_ABS_PATH}/Trelis-plugin
          git submodule update --init

          cd ${PLUGIN_ABS_PATH}/Trelis-plugin
          cp script/*.cmake ${TRELIS_INSTALL_LOC}/MacOS/

          rm -rf bld
          mkdir -pv bld
          cd bld
          cmake .. -DCubit_DIR=${TRELIS_INSTALL_LOC}/MacOS \
                  -DCUBIT_ROOT=${TRELIS_INSTALL_LOC}/MacOS \
                  -DDAGMC_DIR=${PLUGIN_ABS_PATH}/DAGMC \
                  -DCMAKE_BUILD_TYPE=Release \
                  -DCMAKE_INSTALL_PREFIX=${PLUGIN_ABS_PATH}
          make -j
          make install

      - name: Prepare package
        shell: bash
        run: |
          cd ${PLUGIN_ABS_PATH}
          mkdir -p pack/MacOS/plugins/svalinn
          cd pack/MacOS/plugins/svalinn

          # Copy all needed libraries into current directory
          cp -pPv ${PLUGIN_ABS_PATH}/lib/* .

          # Create the Svalinn plugin tarball
          cd ..
          ln -sv svalinn/libsvalinn_plugin.so .
          cd ../..
          tar -czvf svalinn-plugin_mac_17.1.tgz MacOS

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: svalinn-plugin_mac
          path: /Users/runner/work/Trelis-plugin/pack/svalinn-plugin_mac_17.1.tgz

